### ISSUE TITLE
[BUG] Division by zero with criterion's logarithmic plots

### ISSUE THREAD

**Issue by Ekleog** [38/plotters#143]
**Describe the bug**
Running criterion with logarithmic plots, there is a division by zero panic in `plotters-0.2.14/src/coord/logarithmic.rs` line 98:
```rust
fn key_points(&self, max_points: usize) -> Vec<Self::ValueType> {
    let tier_1 = (self.logic.end.as_f64() / self.logic.start.as_f64())
        .log10()
        .abs()
        .floor() as usize;
    let tier_2_density = if max_points < tier_1 {
        0
    } else {
        let density = 1 + (max_points - tier_1) / tier_1;  // <--  here
        let mut exp = 1;
        while exp * 10 <= density {
            exp *= 10;
        }
        exp - 1
    };
    // ...
}
```

My understanding is that the `.floor()` reaches zero when `end / start` is less than 10. I have no idea what code is around it, but maybe it'd make sense to replace it by a `.ceil()`?

Full backtrace:
```
thread 'main' panicked at 'attempt to divide by zero', /home/ekleog/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.2.14/src/coord/logarithmic.rs:98:31
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: <plotters::coord::logarithmic::LogCoord<V> as plotters::coord::ranged::Ranged>::key_points
  15: criterion::plot::plotters_backend::summary::line_comparison
  16: <criterion::plot::plotters_backend::PlottersBackend as criterion::plot::Plotter>::line_comparison
  17: criterion::html::Html::generate_summary
  18: <criterion::html::Html as criterion::report::Report>::summarize
  19: <criterion::report::Reports as criterion::report::Report>::summarize
  20: core::ptr::drop_in_place
  21: smtp_message::main
  22: std::rt::lang_start::{{closure}}
  23: main
  24: __libc_start_main
  25: _start
```

**To Reproduce**
Being in the middle of criterion, I have no idea how to reproduce this, sorry :/

**Version Information**
According to the backtrace, the version criterion uses is `plotters-0.2.14`

**Comment by Ekleog** [comment]
Oh, I forgot: it's still possible to reproduce with criterion with the code at https://github.com/Ekleog/yuubind/commit/e7f2e2f118da40f33f393edd3799a617623cf52f ; by uncommenting these lines https://github.com/Ekleog/yuubind/commit/e7f2e2f118da40f33f393edd3799a617623cf52f#diff-c97503eeb9349e3901778a2cf47a62fdR26-R29 ; at least on my machine.

**Comment by 38** [comment]
Thanks you so much for reporting, I believe this is fixed on master.  

I am going to verify this with your repository and if everything looks good, I am going to have a new minor release for the bug. 

Cheers!

**Comment by 38** [comment]
Hi there, just let you know I've published a new version with this bug fixed.

**Comment by Ekleog** [comment]
Great, thank you! :D
